
# generated by: jx gitops variables
export APP_NAME='jx3-metakube'
export BRANCH_NAME='master'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='ascheman'
export JX_CHART_REPOSITORY='http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/ascheman/jx3-metakube:'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jx3-metakube'
export REPO_OWNER='ascheman'
